### ISSUE TITLE
How?

### ISSUE THREAD

**Issue by MushyToast** [CJdough/.stack#1]
How are we supposed to use it? Nowhere in the documentation does it say how to use this, and although some people _would_ know how to use it, others, like me, don't. You should include somewhere in the documentation on how to use this. Like where do we put the code?

**Comment by MushyToast** [comment]
Ok, well I found out how to use it. But this language is unnecessarily complicated, and the documentation is very unclear. I would recommend furthering the documentation and making the commands a bit more user-friendly to use.

**Comment by CJdough** [comment]
> Ok, well I found out how to use it. But this language is unnecessarily complicated, and the documentation is very unclear. I would recommend furthering the documentation and making the commands a bit more user-friendly to use.

1. the documentation is mainly for me right now so it wasnt meant to be used unless you already had prior knowledge (hence the use of "(kinda)" next to "Documentation")
2. look up the definition of "esolang"

**Comment by MushyToast** [comment]
Well idk, maybe don't upload the repository before it's meant to be used? Or if you do, at least make a small tutorial on how to use it.
No hate tho, its a pretty good project.

**Comment by MushyToast** [comment]
Does print(ASCII) use character codes?

**Comment by CJdough** [comment]
Yes
